title: Thomas Stoeckert's Themed Projects
description: > # this means to ignore newlines until "baseurl:"
  The Blog Home for Thomas Stoeckert's creative projects related to the
  Themed Entertainment industry. 
permalink: ':title/'
baseurl: "/themed-projects" # the subpath of your site, e.g. /blog
url: "https://thomas.stoeckert.us" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Thomas Stoeckert # add your name
author-img: thomas-stoeckert.jpg # add your photo
about-author: A BSCpE Student at UCF who likes to combine storytelling and technology. # add description
social-twitter: thomasstoeckert # add your Twitter handle
social-github: thomasstoeckert # add your Github handle
social-linkedin: thomasstoeckert # add your Linkedin handle
social-email: stoeckertthomas@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
